In [14]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine
from faker import Faker
from pymongo import MongoClient

In [2]:
Restaurantes = pd.read_csv("Restaurantes_base.csv")

C:\Users\santp\AppData\Local\Temp\ipykernel_16244\3666696505.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  Restaurantes = pd.read_csv("Restaurantes_base.csv")

In [3]:
Restaurantes

,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0.0,"Doctors, Traditional Chinese Medicine, Naturop..."
1,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1.0,"Shipping Centers, Local Services, Notaries, Ma..."
2,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0.0,"Department Stores, Shopping, Fashion, Home & G..."
3,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1.0,"Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
4,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1.0,"Brewpubs, Breweries, Food"
...,...,...,...,...,...,...,...,...,...,...,...
202058,Best Brews - Four Points by Sheraton Bengaluru...,"Four Points by Sheraton Bengaluru, 43/3, White...",Whitefield,DES,10000,1.000000,1.000000,4.0,27,1.0,Pubs and bars
202059,Vinod Bar And Restaurant,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Whitefield,DES,10000,1.000000,1.000000,5.0,0,1.0,Pubs and bars
202060,Plunge - Sheraton Grand Bengaluru Whitefield H...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Whitefield,DES,10000,1.000000,1.000000,4.5,0,1.0,Pubs and bars
202061,Chime - Sheraton Grand Bengaluru Whitefield Ho...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Whitefield,DES,10000,1.000000,1.000000,1.0,236,1.0,Pubs and bars
202062,The Nest - The Den Bengaluru,"ITPL Main Road, KIADB Export Promotion Industr...",Whitefield,DES,10000,1.000000,1.000000,2.5,13,1.0,Pubs and bars

In [10]:
USER = 'root'
PASSWORD = '12345'
HOST = 'localhost:3306'
DATABASE = 'Negocios'
engine = create_engine(f'mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}/{DATABASE}')

In [11]:
Restaurantes.to_sql('restaurantes', con=engine, if_exists='replace', index=True)

202063

In [15]:
cliente = MongoClient("mongodb://localhost:27017/")
db = cliente["Negocios"]
coleccion = db["Restaurantes"]

In [ ]:
datos = pd.read_csv("Restaurantes_base.csv").to_dict(orient="records")
coleccion.insert_many(datos)